valid_teams = {'DAL',
               'NYG',
               'PHI',
               'WAS',
               'ATL',
               'CAR',
               'NO',
               'TB',
               'CHI',
               'DET',
               'GB',
               'MIN',
               'ARI',
               'LA',
               'SF',
               'SEA',
               'BUF',
               'MIA',
               'NE',
               'NYJ',
               'HOU',
               'IND',
               'JAC',
               'TEN',
               'BAL',
               'CIN',
               'CLE',
               'PIT',
               'DEN',
               'KC',
               'OAK',
               'LAC'}

# NOTE: typos are intentional.
# These are exactly how the crimes are spelled in the API
valid_crimes = { 'Alcohol',
                 'Resisting arrest',
                 'Theft',
                 'Reckless driving',
                 'DUI, drugs',
                 'Outstanding warrant',
                 'Drugs, gun',
                 'Failure to appear',
                 'Violating court order',
                 'Sex',
                 'Assault, gun',
                 'Obstruction',
                 'Trespassing',
                 'Sexual assault',
                 'Disorderly conduct, sex',
                 'Animal abuse',
                 'Probation violation',
                 'Gun, drugs',
                 'Solicitation',
                 'Disorderly conduct, alcoh',
                 'Domestic dispute',
                 'Domestic violence, gun',
                 'Criminal mischief',
                 'Alcohol, assault',
                 'Assault, alcohol',
                 'Child support',
                 'Public urination',
                 'Harassment',
                 'Indecent exposure',
                 'DUI, gun',
                 'Manslaughter',
                 'Burglary',
                 'Murder, gun',
                 'False information',
                 'Gun, Traffic',
                 'Robbery'
                 'Alcohol, resisting arrest',
                 'Guns, drugs, reckless dri',
                 'Sexual battery',
                 'Animal cruelty, drugs',
                 'Hit and Run',
                 'Suspended license',
                 'Drugs, resisting arrest',
                 'Injury to elderly',
                 'Theft, gun',
                 'Attempted murder',
                 'Traffic warrants',
                 'Battery, resisting arrres',
                 'DUI, manslaughter',
                 'Manslaughter, child abuse',
                 'Burglary, assault',
                 'Eluding police',
                 'Child abuse',
                 'Police interference',
                 'False name',
                 'Reckless driving, drugs',
                 'Domestic',
                 'Gun, privacy invasion',
                 'Guns',
                 'Domestic violence, rape',
                 'Handicap parking',
                 'Animal neglect',
                 'Drugs, licence'
                 'Hit-and-run',
                 'Interfering with police',
                 'Threat',
                 'DUI, drugs, gun',
                 'Licence, guns',
                 'Breach of peace',
                 'DUI, resisting arrest',
                 'Murder',
                 'Weapon',
                 'Burglary, battery',
                 'Evading arrest',
                 'Failure to appear, gun',
                 'Fraud',
                 'Disturbing the peace',
                 'Gun, assault',
                 'Reckless driving, weapon',
                 'Domestic Battery',
                 'Gun, stolen possession',
                 'Resisting officer',
                 'Alcohol, disorderly condu',
                 'Domestic violence, alcoho'
                 'Guns, drugs',
                 'Animal cruelty',
                 'Stalking',
                 'Assasult',
                 'Drugs, reckless driving',
                 'Theft, drugs',
                 'DUI, assault',
                 'Leaving scene.',
                 'Traffic warrant',
                 'Battery, alcohol',
                 'Vandalism',
                 'DUI, drugs',
                 'Burglary, gun',
                 'Evading police',
                 'Pimping',
                 'Coercion, gun',
                 'Property destruction',
                 'Gambling, gun',
                 'Dogfighting',
                 'Reckless endangerment'}

valid_positions = {'WR',
                   'LB',
                   'CB',
                   'RB',
                   'DT',
                   'S',
                   'DE',
                   'OT',
                   'TE',
                   'OG',
                   'QB',
                   'FB',
                   'K',
                   'C',
                   'DB',
                   'P',
                   'DL',
                   'OL',
                   'DE/DT'}